# Generated by Django 6.0.5 on 2026-06-10 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NyRegistrySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.FileField(upload_to='registry/ny/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_format', models.CharField(blank=True, max_length=10)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('columns', models.JSONField(blank=True, default=list)),
                ('key_column', models.CharField(max_length=128)),
                ('status_column', models.CharField(blank=True, max_length=128)),
                ('is_baseline', models.BooleanField(default=False, help_text='Approved snapshot used for next week comparison.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NyRegistryDiffRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_initial_baseline', models.BooleanField(default=False)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('ai_headline', models.CharField(blank=True, max_length=255)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_analysis', models.JSONField(blank=True, default=dict)),
                ('ai_model', models.CharField(blank=True, max_length=64)),
                ('ai_error', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending_review', 'Pending review'), ('approved', 'Approved'), ('failed', 'Failed')], default='pending_review', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('baseline_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diff_runs_as_baseline', to='registry.nyregistrysnapshot')),
                ('new_snapshot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diff_run', to='registry.nyregistrysnapshot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
