# Generated by Django 6.0.5 on 2026-05-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataimport',
            name='extra_tags',
            field=models.JSONField(blank=True, default=list, help_text='Additional tags for this scrape'),
        ),
        migrations.AddField(
            model_name='dataimport',
            name='filter_fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='dataimport',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dataimport',
            name='outscraper_category',
            field=models.CharField(blank=True, help_text='Category/query used in Outscraper (e.g. auto body shop)', max_length=255),
        ),
        migrations.AddField(
            model_name='dataimport',
            name='outscraper_location',
            field=models.CharField(blank=True, help_text='Location filter (e.g. Westchester, NY)', max_length=255),
        ),
        migrations.AddField(
            model_name='dataimport',
            name='outscraper_max_results',
            field=models.PositiveIntegerField(blank=True, help_text='Max entries limit set in Outscraper', null=True),
        ),
        migrations.AddField(
            model_name='dataimport',
            name='outscraper_services',
            field=models.JSONField(blank=True, default=list, help_text='Enrichment services selected in Outscraper'),
        ),
        migrations.AlterField(
            model_name='dataimport',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('awaiting_confirm', 'Awaiting duplicate confirm'), ('parsed', 'Parsed'), ('failed', 'Failed')], default='uploaded', max_length=20),
        ),
    ]
