# Generated by Django 6.0.5 on 2026-05-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0002_dataimport_extra_tags_dataimport_filter_fingerprint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='processing_mode',
            field=models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='manual', help_text='Automatic: fixed columns + one-click processing. Manual: pick columns step-by-step.', max_length=20),
        ),
    ]
