# Generated by Django 6.0.5 on 2026-07-14 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0008_filteranalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataimport',
            name='merge_report',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ImportSourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='imports/sources/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_files', to='pipeline.dataimport')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
