"""
Django settings for datamanagement project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')

# External APIs — set in `.env` (see `.env.example`)
OUTSCRAPER_API_KEY = os.environ.get('OUTSCRAPER_API_KEY', '')
MILLIONVERIFIER_API_KEY = os.environ.get('MILLIONVERIFIER_API_KEY', '')
SMARTLEAD_API_KEY = os.environ.get('SMARTLEAD_API_KEY', '')
PHONE_VALIDATION_API_KEY = os.environ.get('PHONE_VALIDATION_API_KEY', '')
SIMPLETEXTING_API_KEY = os.environ.get('SIMPLETEXTING_API_KEY', '')
GHL_API_KEY = os.environ.get('GHL_API_KEY', '')
GHL_LOCATION_ID = os.environ.get('GHL_LOCATION_ID', '')
XVERIFY_DOMAIN = os.environ.get('XVERIFY_DOMAIN', '')
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY', '')
OPENAI_MODEL = os.environ.get('OPENAI_MODEL', 'gpt-4o-mini')

# Browser automation — headless Chrome by default (set AUTOMATION_HEADLESS_CHROME=false to show window)
AUTOMATION_HEADLESS_CHROME = os.environ.get('AUTOMATION_HEADLESS_CHROME', 'true').strip().lower() not in (
    '0', 'false', 'no', 'off',
)

# ICM Step 3 — visible Chrome + logged-in profile by default
ICM_HEADLESS = os.environ.get('ICM_HEADLESS', 'false').strip().lower() not in (
    '0', 'false', 'no', 'off',
)
ICM_USE_REMOTE_DEBUGGING = os.environ.get('ICM_USE_REMOTE_DEBUGGING', 'false').strip().lower() in (
    '1', 'true', 'yes', 'on',
)
ICM_REMOTE_DEBUGGING_ADDRESS = os.environ.get('ICM_REMOTE_DEBUGGING_ADDRESS', '127.0.0.1:9222')
ICM_CHROME_USER_DATA_DIR = os.environ.get('ICM_CHROME_USER_DATA_DIR', '')
ICM_CHROME_PROFILE_DIRECTORY = os.environ.get('ICM_CHROME_PROFILE_DIRECTORY', '')
ICM_CHROME_PROFILE_NAME = os.environ.get('ICM_CHROME_PROFILE_NAME', '')
ICM_CHROME_PROFILE_EMAIL = os.environ.get('ICM_CHROME_PROFILE_EMAIL', '')
ICM_USE_CHROME_PROFILE = os.environ.get('ICM_USE_CHROME_PROFILE', 'true').strip().lower() not in (
    '0', 'false', 'no', 'off',
)
ICM_LOGIN_EMAIL = os.environ.get('ICM_LOGIN_EMAIL', '')
ICM_LOGIN_PASSWORD = os.environ.get('ICM_LOGIN_PASSWORD', '')
ICM_PAUSE_BETWEEN_SEARCHES = float(os.environ.get('ICM_PAUSE_BETWEEN_SEARCHES', '2.0') or 2.0)

# Caps emails sent to MillionVerifier API only — never truncates cleaned exports.
# Default 5 for safe testing; set MILLIONVERIFIER_UPLOAD_ROW_LIMIT=0 for full runs.
MILLIONVERIFIER_UPLOAD_ROW_LIMIT = int(os.environ.get('MILLIONVERIFIER_UPLOAD_ROW_LIMIT', 5) or 0)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-87nntoay#+j^!ygc(nwmjw7(d@h2%rm^iwep#9(ohofonmd8j^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Required for POST/forms when using ngrok or another HTTPS tunnel (Django 4+ CSRF origin check).
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    'https://*.ngrok-free.app',
    'https://*.ngrok.io',
    'https://*.ngrok.app',
]
_extra_csrf = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
if _extra_csrf:
    CSRF_TRUSTED_ORIGINS.extend(
        o.strip() for o in _extra_csrf.split(',') if o.strip()
    )


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pipeline',
    'registry',
    'automation',
    'dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'datamanagement.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'datamanagement.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

FILE_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024
DATA_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024
