# Generated by Django 6.0.5 on 2026-07-14 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeadWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('master_file', models.FileField(blank=True, upload_to='lead_db/master/%Y/%m/')),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('enriched_count', models.PositiveIntegerField(default=0)),
                ('in_campaign_count', models.PositiveIntegerField(default=0)),
                ('last_merge_report', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadSourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='lead_db/sources/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('source_kind', models.CharField(choices=[('dmv', 'DMV'), ('outscraper', 'Outscraper'), ('beenverified', 'BeenVerified'), ('other', 'Other')], default='other', max_length=32)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_files', to='dashboard.leadworkspace')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LeadRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, max_length=64)),
                ('facility_number', models.CharField(blank=True, db_index=True, max_length=64)),
                ('business_name', models.CharField(blank=True, db_index=True, max_length=512)),
                ('owner_name', models.CharField(blank=True, max_length=512)),
                ('street', models.CharField(blank=True, max_length=512)),
                ('city', models.CharField(blank=True, db_index=True, max_length=255)),
                ('state', models.CharField(blank=True, db_index=True, max_length=64)),
                ('zip_code', models.CharField(blank=True, max_length=32)),
                ('county', models.CharField(blank=True, db_index=True, max_length=128)),
                ('business_type', models.CharField(blank=True, db_index=True, max_length=255)),
                ('industry', models.CharField(blank=True, db_index=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('researched', 'Researched'), ('needs_owner', 'Needs owner'), ('in_campaign', 'In campaign'), ('duplicate', 'Duplicate')], db_index=True, default='needs_owner', max_length=32)),
                ('is_enriched', models.BooleanField(db_index=True, default=False)),
                ('match_key_used', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dupes', to='dashboard.leadrecord')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='dashboard.leadworkspace')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['workspace', 'state', 'county'], name='dashboard_l_workspa_23c1a8_idx'), models.Index(fields=['workspace', 'business_type'], name='dashboard_l_workspa_f2c535_idx')],
            },
        ),
    ]
