# Generated by Django 6.0.5 on 2026-07-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='leadrecord',
            name='dashboard_l_workspa_23c1a8_idx',
        ),
        migrations.RemoveIndex(
            model_name='leadrecord',
            name='dashboard_l_workspa_f2c535_idx',
        ),
        migrations.AddField(
            model_name='leadrecord',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='leadrecord',
            name='search_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='leadworkspace',
            name='columns',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='leadworkspace',
            name='filter_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name='leadrecord',
            index=models.Index(fields=['workspace', 'status'], name='dashboard_l_workspa_943c9f_idx'),
        ),
        migrations.AddIndex(
            model_name='leadrecord',
            index=models.Index(fields=['workspace', 'is_enriched'], name='dashboard_l_workspa_48d19a_idx'),
        ),
        migrations.RemoveField(
            model_name='leadrecord',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='leadrecord',
            name='business_type',
        ),
        migrations.RemoveField(
            model_name='leadrecord',
            name='city',
        ),
        migrations.RemoveField(
            model_name='leadrecord',
            name='county',
        ),
        migrations.RemoveField(
            model_name='leadrecord',
            name='duplicate_of',
        ),
        migrations.RemoveField(
            model_name='leadrecord',
            name='email',
        ),
        migrations.RemoveField(
            model_name='leadrecord',
            name='facility_number',
        ),
        migrations.RemoveField(
            model_name='leadrecord',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='leadrecord',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='leadrecord',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='leadrecord',
            name='state',
        ),
        migrations.RemoveField(
            model_name='leadrecord',
            name='street',
        ),
        migrations.RemoveField(
            model_name='leadrecord',
            name='zip_code',
        ),
    ]
