# Generated by Django 6.0.5 on 2026-07-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_dynamic_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadrecord',
            name='process_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('proceeded', 'Proceeded')], db_index=True, default='pending', max_length=32),
        ),
        migrations.AddField(
            model_name='leadworkspace',
            name='pending_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leadworkspace',
            name='proceeded_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='leadrecord',
            index=models.Index(fields=['workspace', 'process_status'], name='dashboard_l_workspa_6d304c_idx'),
        ),
    ]
