# Generated by Django 6.0.5 on 2026-07-15 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_process_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadWorkspaceAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('proceed', 'Proceed'), ('undo_proceed', 'Undo proceed'), ('merge', 'Merge upload')], db_index=True, max_length=32)),
                ('summary', models.CharField(blank=True, max_length=512)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('record_ids', models.JSONField(blank=True, default=list)),
                ('public_ids', models.JSONField(blank=True, default=list)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('undone_at', models.DateTimeField(blank=True, null=True)),
                ('reverses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_by', to='dashboard.leadworkspaceaction')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='dashboard.leadworkspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
