# Generated by Django 6.0.5 on 2026-07-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_action_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadrecord',
            name='status_millionverifier',
            field=models.CharField(choices=[('pending', 'Pending'), ('proceeded', 'Proceeded')], db_index=True, default='pending', max_length=32),
        ),
        migrations.AddField(
            model_name='leadrecord',
            name='status_simpletexting',
            field=models.CharField(choices=[('pending', 'Pending'), ('proceeded', 'Proceeded')], db_index=True, default='pending', max_length=32),
        ),
        migrations.AddField(
            model_name='leadrecord',
            name='status_smartlead',
            field=models.CharField(choices=[('pending', 'Pending'), ('proceeded', 'Proceeded')], db_index=True, default='pending', max_length=32),
        ),
        migrations.AddField(
            model_name='leadrecord',
            name='status_xverify',
            field=models.CharField(choices=[('pending', 'Pending'), ('proceeded', 'Proceeded')], db_index=True, default='pending', max_length=32),
        ),
    ]
