# Generated by Django 6.0.5 on 2026-07-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_backfill_destination_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadrecord',
            name='status_email_verifier',
            field=models.CharField(choices=[('pending', 'Pending'), ('proceeded', 'Proceeded')], db_index=True, default='pending', max_length=32),
        ),
    ]
