# Generated by Django 6.0.5 on 2026-07-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_email_verifier_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadrecord',
            name='verification_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
