# Generated by Django 6.0.5 on 2026-08-24 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_verification_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartleadCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smartlead_campaign_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SmartleadLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smartlead_lead_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('smartlead_lead_map_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('ghl_contact_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('status', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='dashboard.smartleadcampaign')),
                ('lead_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smartlead_leads', to='dashboard.leadrecord')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SmartleadMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smartlead_message_id', models.CharField(db_index=True, max_length=512, unique=True)),
                ('event_type', models.CharField(choices=[('EMAIL_SENT', 'Email sent'), ('EMAIL_REPLY', 'Email reply')], db_index=True, max_length=32)),
                ('direction', models.CharField(choices=[('outbound', 'Outbound'), ('inbound', 'Inbound')], db_index=True, max_length=16)),
                ('from_email', models.CharField(blank=True, max_length=512)),
                ('to_email', models.CharField(blank=True, max_length=512)),
                ('subject', models.CharField(blank=True, max_length=1024)),
                ('body_text', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('sequence_number', models.PositiveIntegerField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('in_reply_to', models.CharField(blank=True, max_length=512)),
                ('email_references', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('ghl_sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='skipped', max_length=16)),
                ('ghl_sync_attempts', models.PositiveIntegerField(default=0)),
                ('ghl_last_sync_error', models.TextField(blank=True)),
                ('ghl_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dashboard.smartleadcampaign')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dashboard.smartleadlead')),
            ],
            options={
                'ordering': ['sent_at', 'received_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SmartleadWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(blank=True, db_index=True, max_length=64)),
                ('smartlead_message_id', models.CharField(blank=True, db_index=True, max_length=512)),
                ('campaign_id', models.CharField(blank=True, max_length=64)),
                ('lead_id', models.CharField(blank=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('duplicate', 'Duplicate'), ('ignored', 'Ignored'), ('error', 'Error')], db_index=True, default='received', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='dashboard.smartleadmessage')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddIndex(
            model_name='smartleadlead',
            index=models.Index(fields=['campaign', 'smartlead_lead_id'], name='dashboard_s_campaig_6971f9_idx'),
        ),
        migrations.AddConstraint(
            model_name='smartleadlead',
            constraint=models.UniqueConstraint(fields=('campaign', 'email'), name='uq_smartlead_lead_campaign_email'),
        ),
        migrations.AddIndex(
            model_name='smartleadmessage',
            index=models.Index(fields=['lead', 'event_type'], name='dashboard_s_lead_id_574b67_idx'),
        ),
        migrations.AddIndex(
            model_name='smartleadmessage',
            index=models.Index(fields=['campaign', 'event_type'], name='dashboard_s_campaig_b2a11d_idx'),
        ),
    ]
