# Generated by Django 6.0.5 on 2026-06-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('spy_dialer_people', 'Spy Dialer — People')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('headless', models.BooleanField(default=True, help_text='Run Chrome without a visible window.')),
                ('input_file', models.FileField(blank=True, upload_to='automation/inputs/%Y/%m/')),
                ('output_file', models.FileField(blank=True, upload_to='automation/outputs/%Y/%m/')),
                ('params', models.JSONField(blank=True, default=dict)),
                ('log', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('rows_processed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
