# Generated by Django 6.0.5 on 2026-06-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationrun',
            name='column_map',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='automationrun',
            name='control',
            field=models.CharField(choices=[('run', 'Run'), ('pause', 'Pause'), ('stop', 'Stop')], default='run', max_length=8),
        ),
        migrations.AddField(
            model_name='automationrun',
            name='current_row_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='automationrun',
            name='input_columns',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='automationrun',
            name='rows_done',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='automationrun',
            name='rows_failed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='automationrun',
            name='rows_skipped',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='automationrun',
            name='search_mode',
            field=models.CharField(blank=True, choices=[('phone', 'Phone number'), ('people', 'Name + city + state')], max_length=16),
        ),
        migrations.AddField(
            model_name='automationrun',
            name='total_rows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='automationrun',
            name='job_type',
            field=models.CharField(choices=[('spy_dialer', 'Spy Dialer'), ('spy_dialer_people', 'Spy Dialer — People')], max_length=32),
        ),
        migrations.AlterField(
            model_name='automationrun',
            name='status',
            field=models.CharField(choices=[('configuring', 'Awaiting setup'), ('pending', 'Pending'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed'), ('stopped', 'Stopped'), ('cancelled', 'Cancelled')], default='configuring', max_length=16),
        ),
    ]
