# Generated by Django 6.0.5 on 2026-07-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_automationrun_column_map_automationrun_control_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationrun',
            name='job_type',
            field=models.CharField(choices=[('spy_dialer', 'Spy Dialer'), ('spy_dialer_people', 'Spy Dialer — People'), ('icm_personal', 'ICM — Personal contact')], max_length=32),
        ),
    ]
